# Generated by Django 5.0.2 on 2024-02-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoribuku',
            fields=[
                ('kategoriid', models.IntegerField(db_column='KategoriID', primary_key=True, serialize=False)),
                ('namakategori', models.CharField(db_column='NamaKategori', max_length=255)),
            ],
        ),
    ]
