# Generated by Django 5.0.4 on 2024-04-16 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buku', '0001_initial'),
        ('kategoribuku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoribuku_relasi',
            fields=[
                ('kategoribukuid', models.IntegerField(db_column='KategoriBukuID', primary_key=True, serialize=False)),
                ('bukuid', models.ForeignKey(db_column='BukuID', on_delete=django.db.models.deletion.DO_NOTHING, to='buku.buku')),
                ('kategoriid', models.ForeignKey(db_column='KategoriID', on_delete=django.db.models.deletion.DO_NOTHING, to='kategoribuku.kategoribuku')),
            ],
        ),
    ]
