# Generated by Django 5.0.2 on 2024-02-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koleksipribadi',
            fields=[
                ('koleksiid', models.IntegerField(db_column='KoleksiID', primary_key=True, serialize=False)),
                ('bukuid', models.ForeignKey(db_column='BukuID', on_delete=django.db.models.deletion.DO_NOTHING, to='buku.buku')),
            ],
        ),
    ]
