# Generated by Django 5.0.2 on 2024-02-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kategoribuku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('bukuid', models.IntegerField(db_column='BukuID', primary_key=True, serialize=False)),
                ('judul', models.CharField(db_column='Judul', max_length=255)),
                ('penulis', models.CharField(db_column='Penulis', max_length=255)),
                ('penerbit', models.CharField(db_column='Penerbit', max_length=255)),
                ('tahunterbit', models.IntegerField(db_column='TahunTerbit')),
                ('kategoriid', models.ForeignKey(db_column='KategoriID', on_delete=django.db.models.deletion.DO_NOTHING, to='kategoribuku.kategoribuku')),
            ],
        ),
    ]
